<h3>Informações Editar Usuário</h3>
<?php if($this->error): ?>
<p class="error">Havia um ou mais isues com o seu envio. Corrija-os como
indicado abaixo.</p>
<?php endif; ?>
<section>
    <?php
    $form = $this->form;
    $form->prepare();
    $form->setAttribute('action', $this->url('users/user-manager', array('action' => 'process')));
    $form->setAttribute('method', 'post');
    
    echo $this->form()->openTag();
    ?>
    <dl class="zend_form">
        <dt><?php echo $this->formLabel($form->get('name')); ?><dt>
        <?php echo $this->formElement($form->get('id')); ?>
        
        <dd>
            <?php
            echo $this->formElement($form->get('name'));
            echo $this->formElementErrors($form->get('name'));
            ?>
        </dd>
        
        <dt><?php echo $this->formElement($form->get('email')); ?></dt>
        <dd>
            <?php
            echo $this->formElement($form->get('email'));
            echo $this->formElementErrors($form->get('email'));
            ?>
        </dd>
        
        <dd>
            <?php 
            echo $this->formElement($form->get('submit'));
            echo $this->formElementErrors($form->get('submit'));
            ?>
        </dd>
    </dl>
    <?php echo $this->form()->closeTag(); ?>
</section>
